-- FK's --
ALTER TABLE Offer ADD CONSTRAINT FK_OFFER_CATEGORY FOREIGN KEY (offerCategory) REFERENCES DB_Category (Name);
ALTER TABLE Offer ADD CONSTRAINT FK_OFFER_USER FOREIGN KEY (userID) REFERENCES DB_User (userID);