-- FK's --
ALTER TABLE Offer ADD CONSTRAINT FK_OFFER_CATEGORY FOREIGN KEY (offerCategory) REFERENCES DB_Category (Name);

ALTER TABLE DB_NEEDS ADD CONSTRAINT FK_NEED_CATEGORY FOREIGN KEY (category) REFERENCES DB_Category (Id);
ALTER TABLE DB_NEEDS ADD CONSTRAINT FK_NEED_USER FOREIGN KEY (idUser) REFERENCES DB_User(userId);
