-- FK's --
ALTER TABLE DB_OFFERS ADD CONSTRAINT FK_OFFER_CATEGORY FOREIGN KEY (offerCategory) REFERENCES DB_Category(Id);
ALTER TABLE DB_OFFERS ADD CONSTRAINT FK_OFFER_USER FOREIGN KEY (userID) REFERENCES DB_User (userID);

ALTER TABLE DB_NEEDS ADD CONSTRAINT FK_NEED_CATEGORY FOREIGN KEY (category) REFERENCES DB_Category (Id);
ALTER TABLE DB_NEEDS ADD CONSTRAINT FK_NEED_USER FOREIGN KEY (idUser) REFERENCES DB_User(userId);

ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_OFFER FOREIGN KEY (IdOffer) REFERENCES DB_OFFERS(offerId);
ALTER TABLE DB_ANSWER ADD CONSTRAINT FK_ANSWER_NEED FOREIGN KEY (IdNeeds) REFERENCES DB_Needs(Id);

-- Delete FK
ALTER TABLE DB_OFFERS DROP CONSTRAINT FK_OFFER_CATEGORY;
ALTER TABLE DB_OFFERS DROP CONSTRAINT FK_OFFER_USER;

ALTER TABLE DB_NEEDS DROP CONSTRAINT FK_NEED_CATEGORY;
ALTER TABLE DB_NEEDS DROP CONSTRAINT FK_NEED_USER;

ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_OFFER;
ALTER TABLE DB_ANSWER DROP CONSTRAINT FK_ANSWER_NEED;